config/routes.rb
Rails.application.routes.draw do
    root 'quotes#index'
    resource :quotes
    get 'about', to: 'quotes#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
    validates :saying, presence: true, length: { maximum: 140, minimum: 3}
    validates :author, presence: true, length: {maximum: 50, minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    def index
    @quote = Quote.order("RANDOM()").first
    end
    

    def create
        @quote = Quote.create(quote_params)
        if @quote.invalid?
        flash[:error]= '<strong>Could not save </strong> the data you entered is invalid.'
    end
        redirect_to root_path
end

def about
end
    
    private
    
    def quote_params
        params.require( :quote).permit( :saying, :author)
    end
    
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splurty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      
  </head>

  <body>
  
    <header class="row">
    
        <div class= "col-3">
        <%= link_to root_path, class: 'logo' do %>
             <div class= "circle">
                <br />
                You know
                <br />
                You love us
                <br />
                Admit it
            </div>   
          <% end %>
        
        </div>
        
        <div class = "col col-sm-4 hidden-xs-down slogan">
        
            Splurting out advice on Gemini greatness from me, A True Gemini, and others Gemini friends
      
      </div>
      
    <div class ="col-10 offset-1 offset-sm-0 col-sm-5 links">
        
    <!-- Button trigger modal -->
        <%= link_to 'Your 2 Cents', '#', data: {toggle: 'modal', target: '#myModal'} %>
        &nbsp;&nbsp;
        <%= link_to 'About Me', about_path %>
        </div>   
    </header>
    

<!-- Modal -->

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Contribute Your 2 Cents</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">x</span>
        </button>
      </div>

    <%= simple_form_for Quote.new do |f| %>
        <div class="modal-body">   
            <%= f.input :saying, label: "What 2 cents do you want to contribute?", placeholder: "I guess I’m a Gemini through and through, but I’m mercurial. I get bored doing the same things." %>
            <br />
            <%= f.input :author,  label: "Who is adding their 2 cents", placeholder: "Jewel" %>
        </div>
        
        <div class = "modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
      </div>
        <%= f.submit 'Create', class: 'btn btn-danger' %>
        
<% end %>

    </div>
     
        
    
  </div>
</div>
    
    <hr />
    
    <br class ="clear"/>
    
    <div class = "container">
        <% if flash[:error].present? %>
            <div class="col-10 offset-1 alert alert-danger">
                <%= flash[:error].html_safe %>
            </div>
        <% end %>
    
        <%= yield %>  
        
    </div>
    
    
    
    <div class="footer">
    
        <div class="container">
            <div class="row">
            
                <div class="col-12 col-sm-6">
                    <%= link_to "This isn't enough, I need more", root_path, class: 'next-quote' %> 
                    
                </div>
             
                <div class ="col-12 col-sm-6 footer-blurb">
                    Proudly hacked by <a>Keara Harris in a city or island near you </a><br />
                    
                    Want to build your own Splurty Web App - <a href="https://online.bootcampspot.com"> Learn how to code here </a>
               </div>
            </div>
        </div>
    </div>


</body>
  
</html>

app/views/quotes/about.html.erb
<div class= "col-10 offset-1 about">
    <h1 class>About Splurty</h1>
    
    <p>
        Splurty was built by <a target ="_blank" href ="https://github.com/Sirrahk"> Keara </a> a budding web developer and of course True Gemini. The goal of this Splurty app is to try to chage the perception of us Gemini's and to let everyone know how awesome we are.
    </p>
    <br />
    <p>
        This is just the first of many websites to come and with the help of this Web Development Bootcamp, she's learning how to become the world's greatest developer.
     </p>
  <div class ="row">  
  
    <div class="col-12 col-sm-7 offset-sm1 aboutkey">
    
    <h2 class>About Keara Harris</h2>
    <br />

    <p>
        Keara Harris receieved her Bachelor's Degree in Electrical Engineering, from Hampton University, in 2010. In 2012 she became a Patent Examiner at the United States Patent and Trademark office, where she worked, for 6 years, on Patents pertaining to Printing and Faxing and later moved to the area of Speech, Audio and Linguistics (think Siri, Machine learning, neural networks, and more). Now she no longer works at the Patent Office but has decided to embark on this Coding journey to get back to some of what she enjoyed, become a freelance web developer and use coding to make a difference in humanity.
    
    </p>
     
    </div>    
   </div>     
</div>

<br class ="clear">
<br />
<br />
<br />
<br />

app/views/quotes/index.html.erb
<h2>
    <span>SPLURTY / No. <%= @quote.id %></span>
    Here's the <u> best unsolicited Gemini advice</u> you can  get!
</h2>

<br class="clear" />
<br />
<br />

<h1><%= @quote.saying %></h1>
<h2 class ="float-right">- <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />